// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalpPdSjpoY2tvI68ULHWcNU4KD8TLDOQ',
    appId: '1:410139493121:web:298e9793ca1d5518dd5100',
    messagingSenderId: '410139493121',
    projectId: 'melanospy-6fe2a',
    authDomain: 'melanospy-6fe2a.firebaseapp.com',
    storageBucket: 'melanospy-6fe2a.appspot.com',
    measurementId: 'G-N348LDS99G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsRN3PWTh3L80Iw2TvMMH4mmRG-JXcEQ',
    appId: '1:410139493121:android:9bef7ae10158832fdd5100',
    messagingSenderId: '410139493121',
    projectId: 'melanospy-6fe2a',
    storageBucket: 'melanospy-6fe2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7MXdKAXLQMUD65EGUoKWz45w64piVx4',
    appId: '1:410139493121:ios:335f94234cbb2f22dd5100',
    messagingSenderId: '410139493121',
    projectId: 'melanospy-6fe2a',
    storageBucket: 'melanospy-6fe2a.appspot.com',
    iosBundleId: 'com.example.melanospy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7MXdKAXLQMUD65EGUoKWz45w64piVx4',
    appId: '1:410139493121:ios:6bb57cb9d9f47efcdd5100',
    messagingSenderId: '410139493121',
    projectId: 'melanospy-6fe2a',
    storageBucket: 'melanospy-6fe2a.appspot.com',
    iosBundleId: 'com.example.melanospy.RunnerTests',
  );
}
